import type { DiscQuestion, MbtiQuestion } from "./types";

export const mbtiQuestions: MbtiQuestion[] = [
  { id: "q1", dimension: "EI", positive: "E", prompt: "连续讨论之后，哪种恢复节奏更接近你？", leftLabel: "独处整理后恢复更快", rightLabel: "继续交换想法更有劲" , example: "例如：连续参加两个讨论会之后，你是想先安静整理笔记，还是继续和同事边聊边消化？" },
  { id: "q2", dimension: "SN", positive: "N", prompt: "接到新任务时，你更常先抓哪一层信息？", leftLabel: "条件、步骤和已知边界", rightLabel: "趋势、可能和延展空间" , example: "例如：老板交代一个新项目，你是先问预算、时间和流程，还是先想它未来能扩展成什么？" },
  { id: "q3", dimension: "TF", positive: "T", prompt: "做取舍时，你更常先采用哪种判断入口？", leftLabel: "人的处境和接受度", rightLabel: "事实、规则和代价" , example: "例如：两个方案都可行时，你是先看团队成员是否容易接受，还是先比较成本和规则边界？" },
  { id: "q4", dimension: "JP", positive: "J", prompt: "面对一段新的行程或任务，你更偏好的开局方式是？", leftLabel: "先保留弹性边走边看", rightLabel: "先安排关键节点" , example: "例如：周末出行前，你是只定大方向保留变化，还是先把交通和时间点排清？" },
  { id: "q5", dimension: "EI", positive: "I", prompt: "表达复杂想法时，哪种方式更自然？", leftLabel: "在交流中逐步成形", rightLabel: "先独自想清再表达" , example: "例如：要说明一个复杂判断时，你是边讲边修正，还是先写几条要点再开口？" },
  { id: "q6", dimension: "SN", positive: "S", prompt: "评估一个方案时，你更容易先被哪类内容说服？", leftLabel: "未来空间和整体构想", rightLabel: "案例、数据和执行路径" , example: "例如：听产品方案时，你是更容易被愿景图打动，还是被真实案例和执行步骤打动？" },
  { id: "q7", dimension: "TF", positive: "F", prompt: "方案讨论出现分歧时，你更常先关注哪一面？", leftLabel: "原则、边界和取舍", rightLabel: "关系、感受和节奏" , example: "例如：同事意见不同，你是先把原则和取舍讲清，还是先照顾对方当下的感受节奏？" },
  { id: "q8", dimension: "JP", positive: "P", prompt: "项目刚开始时，哪种推进状态更适合你？", leftLabel: "先收敛范围和时间表", rightLabel: "先保留探索余地" , example: "例如：项目启动第一周，你是想先定范围和时间表，还是先试几种方向再收口？" },
  { id: "q9", dimension: "EI", positive: "E", prompt: "遇到卡住的问题时，你更常用哪种方式打开思路？", leftLabel: "安静推演一段时间", rightLabel: "找人聊一轮" , example: "例如：方案卡住时，你是先一个人画图推演，还是找人白板讨论一轮？" },
  { id: "q10", dimension: "SN", positive: "N", prompt: "阅读材料时，你更容易注意哪类线索？", leftLabel: "具体事实和字面信息", rightLabel: "隐含假设和深层模式" , example: "例如：读一份行业报告，你是先抓数字和事实，还是先看背后趋势和未说出的假设？" },
  { id: "q11", dimension: "TF", positive: "T", prompt: "别人请你给建议时，你更常先给哪类反馈？", leftLabel: "情绪支持和处境回应", rightLabel: "结构问题和改进路径" , example: "例如：朋友问你意见，你是先回应他的处境，还是先指出问题结构和下一步？" },
  { id: "q12", dimension: "JP", positive: "J", prompt: "处理待办事项时，哪种状态更让你顺手？", leftLabel: "按状态灵活推进", rightLabel: "列清单逐项收尾" , example: "例如：一天有很多小事，你是按状态灵活切换，还是列成清单逐个完成？" },
  { id: "q13", dimension: "EI", positive: "I", prompt: "参加大型聚会之后，你通常更需要什么？", leftLabel: "继续保留热闹状态", rightLabel: "留出安静时间" , example: "例如：聚餐结束后，你是还想续摊聊天，还是想回家安静一会儿？" },
  { id: "q14", dimension: "SN", positive: "S", prompt: "学习新工具时，哪种路径更符合你？", leftLabel: "先理解整体框架", rightLabel: "先照步骤跑通一次" , example: "例如：学一个新软件，你是先看整体逻辑，还是先跟教程做出第一个结果？" },
  { id: "q15", dimension: "TF", positive: "F", prompt: "观察团队状态时，你更常先看哪一项？", leftLabel: "目标、分工和绩效节奏", rightLabel: "氛围、照应和合作感" , example: "例如：观察一个团队，你是先看目标分工是否顺，还是先看成员之间配合是否舒服？" },
  { id: "q16", dimension: "JP", positive: "P", prompt: "临时出现新机会时，你更倾向于怎么处理？", leftLabel: "先维护原有安排", rightLabel: "先试探新机会" , example: "例如：原计划已排好但出现新邀约，你是倾向保持原安排，还是先看看新机会值不值得改？" },
  { id: "q17", dimension: "EI", positive: "E", prompt: "多人讨论的现场通常给你带来什么感受？", leftLabel: "信息较多，需要消化", rightLabel: "能量上升，想参与" , example: "例如：多人头脑风暴时，你是觉得信息太密要回去消化，还是越聊越想参与？" },
  { id: "q18", dimension: "SN", positive: "N", prompt: "看到一件小事时，你更常怎么理解它？", leftLabel: "先按当前事项处理", rightLabel: "联想到更大的模式" , example: "例如：看到一次客户投诉，你是先处理这件事本身，还是联想到产品机制的长期问题？" },
  { id: "q19", dimension: "TF", positive: "T", prompt: "团队意见相撞时，你更常先问什么？", leftLabel: "各方各自看重什么", rightLabel: "哪种判断更可验证" , example: "例如：会议上观点相撞，你是先听各方在乎什么，还是先判断哪种说法更能验证？" },
  { id: "q20", dimension: "JP", positive: "J", prompt: "临近截止日期前，你更偏好的工作状态是？", leftLabel: "临近时集中冲刺", rightLabel: "主要内容较早成型" , example: "例如：报告下周交，你是喜欢最后两天集中爆发，还是提前几天先形成主体？" },
  { id: "q21", dimension: "EI", positive: "I", prompt: "社交时间有限时，你更愿意如何分配？", leftLabel: "多认识几类人", rightLabel: "和少数人深聊" , example: "例如：参加行业活动，你是想多交换几张名片，还是和一两个人聊深一点？" },
  { id: "q22", dimension: "SN", positive: "S", prompt: "听到一个新设想时，你更常先追问什么？", leftLabel: "它还能延展到哪里", rightLabel: "资源、流程和时间" , example: "例如：别人提出新点子，你是先追问还能怎么展开，还是先问时间、人手和流程？" },
  { id: "q23", dimension: "TF", positive: "F", prompt: "沟通一个不同意见时，你更常先调整哪部分？", leftLabel: "论点顺序和推理链条", rightLabel: "表达语气和对方感受" , example: "例如：要提反对意见，你是先整理论证顺序，还是先想对方怎样更容易听进去？" },
  { id: "q24", dimension: "JP", positive: "P", prompt: "计划执行中出现新办法时，你更偏好哪种处理？", leftLabel: "沿原计划小幅修正", rightLabel: "重新比较后再调整" , example: "例如：执行中发现新工具，你是倾向小幅纳入，还是愿意重新比较整体做法？" },
  { id: "q25", dimension: "EI", positive: "E", prompt: "进入陌生小组时，你更常怎样开始？", leftLabel: "先观察他人的节奏", rightLabel: "主动开启一两个话题" , example: "例如：进入陌生饭局，你是先听大家怎么聊，还是主动抛出一个轻松话题？" },
  { id: "q26", dimension: "SN", positive: "N", prompt: "面对一个领域话题时，你更容易被哪类内容吸引？", leftLabel: "细节、案例和操作方式", rightLabel: "趋势、模型和跨界类比" , example: "例如：研究一个行业，你是先看真实案例和操作细节，还是先看趋势模型和跨界类比？" },
  { id: "q27", dimension: "TF", positive: "T", prompt: "收到反馈时，哪种形式更便于你吸收？", leftLabel: "语气温和、留有铺垫", rightLabel: "直说重点、边界清楚" , example: "例如：别人指出你的问题，你是更能接收温和铺垫，还是更喜欢对方直接说重点？" },
  { id: "q28", dimension: "JP", positive: "J", prompt: "出门旅行前，你更喜欢哪种准备方式？", leftLabel: "到当地再决定细节", rightLabel: "先定好关键路线" , example: "例如：旅行前，你是只订第一晚酒店，还是把主要路线和关键票务都定好？" },
  { id: "q29", dimension: "EI", positive: "I", prompt: "确认自己的想法时，你更常依赖哪种过程？", leftLabel: "说出来之后逐步成形", rightLabel: "独自整理后更清晰" , example: "例如：你对一件事还没想明白，是更想找人说说，还是先自己写下来整理？" },
  { id: "q30", dimension: "SN", positive: "S", prompt: "比较两个方案时，你更偏好哪种表达？", leftLabel: "启发性强，打开想象", rightLabel: "边界清楚，便于执行" , example: "例如：看方案文档，你是喜欢它能启发新想法，还是喜欢它边界清楚可直接执行？" },
  { id: "q31", dimension: "TF", positive: "F", prompt: "听到别人的困难时，你更常先进入哪种状态？", leftLabel: "分析原因和可选动作", rightLabel: "代入处境和情绪" , example: "例如：朋友遇到困难，你是先帮他梳理原因办法，还是先陪他把感受说出来？" },
  { id: "q32", dimension: "JP", positive: "P", prompt: "安排一天时间时，哪种结构更适合你？", leftLabel: "时段排得比较满", rightLabel: "留出可移动空白" , example: "例如：安排一天日程，你是喜欢时段紧凑效率高，还是留几块空白方便调整？" },
  { id: "q33", dimension: "EI", positive: "E", prompt: "校准一个新判断时，你更常借助什么？", leftLabel: "内部标准和独自复盘", rightLabel: "外部回应和现场反馈" , example: "例如：形成新判断时，你是先按自己的标准复盘，还是更想听几个人的即时反馈？" },
  { id: "q34", dimension: "SN", positive: "N", prompt: "面对尚未成形的想法，你更常有什么反应？", leftLabel: "等它更成熟再投入", rightLabel: "愿意先沿方向探索" , example: "例如：一个方向还很粗糙，你是等信息成熟再投入，还是愿意先试探性探索？" },
  { id: "q35", dimension: "TF", positive: "T", prompt: "规则和个别情况有张力时，你更常先看哪边？", leftLabel: "当下人的具体处境", rightLabel: "规则的一致性" , example: "例如：制度安排碰到个别情况，你是先看这个人的处境，还是先看规则是否一致？" },
  { id: "q36", dimension: "JP", positive: "J", prompt: "工作空间或文件结构对你的影响更接近哪种？", leftLabel: "开放随手也能推进", rightLabel: "有序分类更顺手" , example: "例如：电脑文件很多时，你是随手放也能找，还是分类清楚才更容易进入状态？" },
  { id: "q37", dimension: "EI", positive: "I", prompt: "表达观点前，你更常处在哪种节奏？", leftLabel: "想到就先抛出来", rightLabel: "选好时机再说" , example: "例如：会议里突然有想法，你是先抛出来再打磨，还是等找到合适时机再说？" },
  { id: "q38", dimension: "SN", positive: "S", prompt: "做判断时，你更常优先检查什么？", leftLabel: "方向和整体走向", rightLabel: "细节、数字和来源" , example: "例如：判断一个项目是否靠谱，你是先看方向是否对，还是先查数据来源和细节？" },
  { id: "q39", dimension: "TF", positive: "F", prompt: "讨论有冲突时，你更常如何控制表达？", leftLabel: "先把分歧说清", rightLabel: "同时保留对方余地" , example: "例如：争论升温时，你是先把分歧点讲透，还是同时给对方保留转圜空间？" },
  { id: "q40", dimension: "JP", positive: "P", prompt: "寻找做事路径时，哪种方式更接近你？", leftLabel: "先规划路径再行动", rightLabel: "行动中逐渐找路径" , example: "例如：开始做视频脚本，你是先搭完整大纲，还是先写几段再慢慢找到结构？" },
  { id: "q41", dimension: "EI", positive: "E", prompt: "在陌生环境里，你通常更接近哪种状态？", leftLabel: "保持旁观更久", rightLabel: "较快参与进去" , example: "例如：到了新工作坊，你是先在旁边观察久一点，还是很快加入讨论？" },
  { id: "q42", dimension: "SN", positive: "N", prompt: "处理眼前问题时，你更常把注意力放在哪里？", leftLabel: "当下可处理的部分", rightLabel: "放大后的长期变化" , example: "例如：处理一个小问题时，你是先把眼前修好，还是会顺手推演三个月后的影响？" },
  { id: "q43", dimension: "TF", positive: "T", prompt: "评价一个行动时，你更常先看哪一面？", leftLabel: "动机和关系影响", rightLabel: "结果和边界影响" , example: "例如：评价一次合作，你是先看彼此动机和关系感受，还是先看结果和边界？" },
  { id: "q44", dimension: "JP", positive: "J", prompt: "做复杂事情时，你更喜欢怎样开始？", leftLabel: "先做起来再修标准", rightLabel: "先定义完成标准" , example: "例如：写一份复杂报告，你是先写起来再定标准，还是先定义完成样子？" },
  { id: "q45", dimension: "EI", positive: "I", prompt: "维系关系时，哪种模式更适合你？", leftLabel: "广泛保持轻连接", rightLabel: "少数关系投入更深" , example: "例如：维护朋友圈时，你是喜欢广泛轻联系，还是把精力放在少数深关系？" },
  { id: "q46", dimension: "SN", positive: "S", prompt: "跟踪进展时，你更偏好哪类信号？", leftLabel: "灵感突破和方向变化", rightLabel: "可复盘、可追踪的结果" , example: "例如：推进创作项目，你是更看重灵感突然打开，还是更看重每周可复盘的进展？" },
  { id: "q47", dimension: "TF", positive: "F", prompt: "别人情绪强烈时，你更常先回应什么？", leftLabel: "事实经过和下一步", rightLabel: "对方此刻的感受" , example: "例如：同事情绪很满，你是先问发生了什么和下一步，还是先回应他的感受？" },
  { id: "q48", dimension: "JP", positive: "P", prompt: "事情处在未完成阶段时，你更常如何看待？", leftLabel: "希望尽快收口", rightLabel: "能接受继续演化" , example: "例如：作品还没成型时，你是想尽快收口成版本，还是愿意继续让它演化？" },
  { id: "q49", dimension: "EI", positive: "E", prompt: "团队现场里，你更常自然承担哪类角色？", leftLabel: "观察、记录和补充", rightLabel: "带动话题和连接人" , example: "例如：团队讨论冷场时，你是更常记录补充，还是更常接话把气氛带起来？" },
  { id: "q50", dimension: "SN", positive: "N", prompt: "讨论暂未落地的抽象问题时，你通常更接近哪种状态？", leftLabel: "希望尽快回到应用", rightLabel: "愿意继续展开概念" , example: "例如：聊一个暂时落不了地的概念，你是想拉回应用，还是愿意继续展开可能性？" },
  { id: "q51", dimension: "TF", positive: "T", prompt: "听别人表达观点时，你更先注意哪部分？", leftLabel: "对方语气和互动感", rightLabel: "论证结构和自洽性" , example: "例如：听一个人发表观点，你是先感受他说话方式，还是先检查论证是否连贯？" },
  { id: "q52", dimension: "JP", positive: "J", prompt: "面对迟到、临时变更或拖延时，你更常如何反应？", leftLabel: "结合现场弹性处理", rightLabel: "希望重新对齐安排" , example: "例如：会议临时改时间，你是比较容易弹性处理，还是希望重新把安排对齐？" },
  { id: "q53", dimension: "EI", positive: "I", prompt: "呈现复杂想法时，哪种载体更适合你？", leftLabel: "现场讲述和互动", rightLabel: "文字或整理后的表达" , example: "例如：解释复杂想法时，你是更适合现场互动讲，还是先写成文字更准确？" },
  { id: "q54", dimension: "SN", positive: "S", prompt: "面对听起来很有吸引力的新想法，你更常先做什么？", leftLabel: "先沿方向想象可能", rightLabel: "先找依据和样例" , example: "例如：听到一个很有吸引力的新点子，你是先顺着想象，还是先找样例依据？" },
  { id: "q55", dimension: "TF", positive: "F", prompt: "表达不同看法前，你更常先调整哪一点？", leftLabel: "观点是否简洁有力", rightLabel: "对方是否容易接住" , example: "例如：表达不同看法前，你是先想观点怎样更简洁，还是先想对方怎样更好接住？" },
  { id: "q56", dimension: "JP", positive: "P", prompt: "多个选项同时存在时，你更偏好哪种状态？", leftLabel: "尽早收敛成一个选择", rightLabel: "多保留一段比较时间" , example: "例如：有三个可选方案时，你是想早点定一个，还是愿意多比较一段时间？" },
  { id: "q57", dimension: "EI", positive: "E", prompt: "获得新信息后，你更常先怎么处理？", leftLabel: "先自己消化一轮", rightLabel: "马上找人交换看法" , example: "例如：看到一条新信息，你是先自己消化，还是马上想找人交换看法？" },
  { id: "q58", dimension: "SN", positive: "N", prompt: "解决现实问题时，你更常从哪里找启发？", leftLabel: "同领域经验和样例", rightLabel: "跨领域类比和模型" , example: "例如：解决一个运营问题，你是先查同行做法，还是先从别的行业借模型？" },
  { id: "q59", dimension: "TF", positive: "T", prompt: "给别人反馈时，你更偏好哪种起点？", leftLabel: "先给支持和鼓励", rightLabel: "先给清楚可改的点" , example: "例如：给同事反馈，你是先肯定支持，再说建议，还是先说最可改的一点？" },
  { id: "q60", dimension: "JP", positive: "P", prompt: "推进一条路线时，哪种体验更吸引你？", leftLabel: "按路线逐步完成", rightLabel: "探索中发现新收获" , example: "例如：做一条内容路线，你是享受按计划完成，还是享受途中发现新方向？" },
];

export const discQuestions: DiscQuestion[] = [
  { id: "d1", dimension: "D", prompt: "任务目标不清时，哪种开局更自然？", leftLabel: "先听清背景和各方顾虑", rightLabel: "先收束目标和结果标准", example: "例如：接到新项目后，是先理解上下文，还是先把交付标准问清。" },
  { id: "d2", dimension: "I", prompt: "讨论现场变安静时，哪种介入更顺手？", leftLabel: "先观察大家为何沉默", rightLabel: "先抛出话题带动交流", example: "例如：会议冷场时，是先判断气氛，还是先用例子把话接起来。" },
  { id: "d3", dimension: "S", prompt: "团队节奏突然加快时，哪种关注更靠前？", leftLabel: "先看关键结果能否赶上", rightLabel: "先看多数人能否跟上", example: "例如：项目提速后，是先盯交付节点，还是先同步信息和过渡节奏。" },
  { id: "d4", dimension: "C", prompt: "听到一个新方案时，哪种入口更自然？", leftLabel: "先看方向是否值得推进", rightLabel: "先看依据和边界是否清楚", example: "例如：别人提出方案后，是先判断价值，还是先核对数据来源和限制。" },
  { id: "d5", dimension: "D", prompt: "截止时间接近时，哪种处理更符合习惯？", leftLabel: "先协调资源减少阻力", rightLabel: "先确定动作快速推进", example: "例如：报告快到期时，是先安排协作，还是先把关键结论推出来。" },
  { id: "d6", dimension: "I", prompt: "想法还没完全成熟时，哪种整理更自然？", leftLabel: "先自己写清楚再交流", rightLabel: "先讲出来借反馈成形", example: "例如：新点子刚出现时，是先独自整理，还是先找人聊一轮。" },
  { id: "d7", dimension: "S", prompt: "同事状态波动时，哪种反应更靠前？", leftLabel: "先拆问题和下一步动作", rightLabel: "先稳住对方节奏和感受", example: "例如：同事推进吃力时，是先分析阻塞，还是先让对方缓一缓说清楚。" },
  { id: "d8", dimension: "C", prompt: "采用新工具前，哪种确认更重要？", leftLabel: "先看能否带来实际效率", rightLabel: "先看限制、文档和小样", example: "例如：换工具前，是先试效率提升，还是先确认风险和兼容性。" },
  { id: "d9", dimension: "D", prompt: "会议绕圈时，哪种方式更自然？", leftLabel: "先让不同意见讲完整", rightLabel: "先把分歧收成决策点", example: "例如：讨论没有结论时，是先继续听完，还是先列出需要拍板的事项。" },
  { id: "d10", dimension: "I", prompt: "写方案时，哪种检查更靠前？", leftLabel: "结构是否严整完整", rightLabel: "别人是否容易理解接受", example: "例如：写完初稿后，是先检查逻辑层次，还是先想读者能否听进去。" },
  { id: "d11", dimension: "S", prompt: "合作方式刚跑顺时，哪种倾向更强？", leftLabel: "趁热继续优化流程", rightLabel: "先稳定运行一段时间", example: "例如：团队形成默契后，是继续调优，还是先让节奏稳定下来。" },
  { id: "d12", dimension: "C", prompt: "处理复杂材料时，哪种开局更顺手？", leftLabel: "先抓主线和关键判断", rightLabel: "先建目录和核对清单", example: "例如：整理合规材料时，是先看主题，还是先定版本、目录和检查点。" },
  { id: "d13", dimension: "D", prompt: "出现合作机会时，哪种判断更靠前？", leftLabel: "先看关系和长期空间", rightLabel: "先看投入产出和路径", example: "例如：有人提出合作时，是先看关系价值，还是先估成本收益。" },
  { id: "d14", dimension: "I", prompt: "陌生场合刚开始时，哪种状态更自然？", leftLabel: "先观察规则和人群节奏", rightLabel: "先找轻松话题建立连接", example: "例如：参加活动时，是先看大家怎么交流，还是先开一个自然话题。" },
  { id: "d15", dimension: "S", prompt: "多人协作中，哪类角色更常出现？", leftLabel: "推进节点和结果收敛", rightLabel: "补位承接和保持连续", example: "例如：协作中出现空档时，是先催下一步，还是先补信息和接遗漏。" },
  { id: "d16", dimension: "C", prompt: "别人给出结论时，哪种追问更自然？", leftLabel: "这个结论能带来什么行动", rightLabel: "这个结论依据是否充分", example: "例如：听到判断后，是先问怎么做，还是先问样本、假设和反例。" },
  { id: "d17", dimension: "D", prompt: "合作效率下降时，哪种做法更接近？", leftLabel: "先私下了解各方状态", rightLabel: "先安排对齐会讲清问题", example: "例如：项目拖慢时，是先摸清原因，还是先把问题摆上桌面。" },
  { id: "d18", dimension: "I", prompt: "表达复杂观点时，哪种目标更靠前？", leftLabel: "先保持定义准确", rightLabel: "先让人抓住记忆点", example: "例如：讲复杂模型时，是先讲精确定义，还是先用一句容易记住的话打开。" },
  { id: "d19", dimension: "S", prompt: "计划需要调整时，哪种顺序更自然？", leftLabel: "先判断新方案价值", rightLabel: "先安排过渡减少摩擦", example: "例如：路线变化时，是先比较收益，还是先说明变化对大家的影响。" },
  { id: "d20", dimension: "C", prompt: "报告临近发出前，哪种检查更重要？", leftLabel: "核心观点是否有力", rightLabel: "数字口径是否一致", example: "例如：材料发送前，是先看结论力度，还是先核标题、数字、附件和格式。" },
  { id: "d21", dimension: "D", prompt: "多个想法同时出现时，哪种处理更自然？", leftLabel: "先保留几条继续比较", rightLabel: "先选一条做成版本", example: "例如：内容选题很多时，是多留几项观察，还是先定一个推进。" },
  { id: "d22", dimension: "I", prompt: "讲项目时，哪种表达更顺手？", leftLabel: "先讲背景、结构和依据", rightLabel: "先讲故事、画面和类比", example: "例如：向别人介绍项目时，是先铺逻辑，还是先用画面感让人进入。" },
  { id: "d23", dimension: "S", prompt: "临时邀约和原计划冲突时，哪种考虑更靠前？", leftLabel: "先看新机会是否值得改", rightLabel: "先看原承诺是否受影响", example: "例如：已有安排时收到邀约，是先评估新机会，还是先维护已承诺事项。" },
  { id: "d24", dimension: "C", prompt: "需求看起来简单时，哪种动作更自然？", leftLabel: "先快速做一个可用版本", rightLabel: "先确认口径和边界条件", example: "例如：别人说做个小页面时，是先开做，还是先确认范围和验收标准。" },
  { id: "d25", dimension: "D", prompt: "选项迟迟无法收敛时，哪种状态更常见？", leftLabel: "继续协调直到分歧变小", rightLabel: "给出判断承担推进压力", example: "例如：三个方案都有人支持时，是继续协调，还是先提出一个明确选择。" },
  { id: "d26", dimension: "I", prompt: "讨论变僵时，哪种调整更自然？", leftLabel: "先回到事实和议程", rightLabel: "先换说法让交流继续", example: "例如：会议气氛紧时，是拉回问题本身，还是换个角度让对话恢复。" },
  { id: "d27", dimension: "S", prompt: "上线新流程前，哪种准备更靠前？", leftLabel: "先定义成效指标", rightLabel: "先安排培训和反馈入口", example: "例如：流程上线时，是先看成效怎么衡量，还是先看大家怎么适应。" },
  { id: "d28", dimension: "C", prompt: "评价一个趋势时，哪种材料更有说服力？", leftLabel: "真实变化和机会窗口", rightLabel: "数据样本和限制条件", example: "例如：判断行业趋势时，是先看机会变化，还是先看证据链是否够稳。" },
  { id: "d29", dimension: "D", prompt: "资源有限时，哪种取舍更自然？", leftLabel: "尽量保留更多可能性", rightLabel: "砍掉低价值动作保主线", example: "例如：时间不够时，是多保留选项，还是直接删减边缘功能。" },
  { id: "d30", dimension: "I", prompt: "团队疲惫时，哪种补能更常用？", leftLabel: "先减少任务复杂度", rightLabel: "先用鼓励和轻松表达带动", example: "例如：大家状态低时，是先降负荷，还是先把气氛往前带一点。" },
  { id: "d31", dimension: "S", prompt: "对方表达很慢时，哪种回应更接近？", leftLabel: "适时帮他提炼重点", rightLabel: "耐心等他说完整", example: "例如：别人讲得绕时，是帮他收束，还是先让他完整表达。" },
  { id: "d32", dimension: "C", prompt: "关键交付完成后，哪种动作更自然？", leftLabel: "先交给别人看整体效果", rightLabel: "先自己复核细节错误", example: "例如：材料完成后，是先征求整体反馈，还是先逐项核对。" },
  { id: "d33", dimension: "D", prompt: "面对高难度任务时，哪种吸引更强？", leftLabel: "稳定完成带来的确定感", rightLabel: "突破限制带来的挑战感", example: "例如：任务很难但价值大时，是先看能否稳妥完成，还是被挑战激发。" },
  { id: "d34", dimension: "I", prompt: "跨团队合作时，哪种工作更自然？", leftLabel: "先厘清职责和接口", rightLabel: "先找到共同语言", example: "例如：两个团队刚合作时，是先定边界，还是先帮双方建立连接。" },
  { id: "d35", dimension: "S", prompt: "长期项目推进时，哪种节奏更舒服？", leftLabel: "阶段性冲刺打开局面", rightLabel: "持续小步建立可靠结果", example: "例如：长期任务里，是喜欢集中突破，还是稳定推进。" },
  { id: "d36", dimension: "C", prompt: "制度更新后，哪种反应更自然？", leftLabel: "先看对业务目标的影响", rightLabel: "先弄清新旧差异范围", example: "例如：规则变化时，是先看影响什么结果，还是先整理条款变化。" },
  { id: "d37", dimension: "D", prompt: "任务卡住几天后，哪种介入更接近？", leftLabel: "先等信息再成熟一点", rightLabel: "先找阻塞点和负责人", example: "例如：事情停住时，是继续观察，还是把卡点和责任重新对齐。" },
  { id: "d38", dimension: "I", prompt: "讲完方案后，哪种反馈更受关注？", leftLabel: "对方是否指出漏洞", rightLabel: "对方是否愿意继续参与", example: "例如：讲完后，是更看重被挑错，还是更看重对方被调动起来。" },
  { id: "d39", dimension: "S", prompt: "不显眼的小承诺出现时，哪种处理更自然？", leftLabel: "按重要性重新排序", rightLabel: "尽量按约定稳定完成", example: "例如：小事很杂时，是按价值重排，还是尽量兑现已经答应的事。" },
  { id: "d40", dimension: "C", prompt: "别人说差不多就行时，哪种反应更接近？", leftLabel: "先按可用程度推进", rightLabel: "先问清差不多的标准", example: "例如：要求含混时，是先做出版本，还是先确认质量边界。" },
  { id: "d41", dimension: "D", prompt: "项目受条件限制时，哪种思路更靠前？", leftLabel: "先调整预期降低消耗", rightLabel: "先寻找突破限制的抓手", example: "例如：预算或人手卡住时，是先缩范围，还是先找改变局面的办法。" },
  { id: "d42", dimension: "I", prompt: "做内容标题时，哪种判断更自然？", leftLabel: "标题是否准确覆盖内容", rightLabel: "标题是否容易被记住", example: "例如：定标题时，是先看准确性，还是先看传播感和节奏。" },
  { id: "d43", dimension: "S", prompt: "伙伴忙不过来时，哪种帮法更接近？", leftLabel: "先帮他确定优先级", rightLabel: "先接住一部分细节", example: "例如：同伴压力大时，是先帮他排序，还是先分担可接手的内容。" },
  { id: "d44", dimension: "C", prompt: "一次流程跑完后，哪种收尾更自然？", leftLabel: "先复盘结果和收益", rightLabel: "先沉淀模板和检查项", example: "例如：做完活动后，是先看成效，还是先整理下次可复用的步骤。" },
  { id: "d45", dimension: "D", prompt: "意见无法全部兼顾时，哪种取舍更接近？", leftLabel: "尽量多留转圜空间", rightLabel: "选择能让任务前进的方案", example: "例如：各方诉求冲突时，是继续协调余地，还是先让任务往前走。" },
  { id: "d46", dimension: "I", prompt: "新成员加入时，哪种支持更自然？", leftLabel: "先说明规则和职责", rightLabel: "先帮助理解团队语言", example: "例如：新人进来时，是先讲流程边界，还是先帮他融入交流方式。" },
  { id: "d47", dimension: "S", prompt: "评价一次合作时，哪种信号更靠前？", leftLabel: "这次结果是否达到目标", rightLabel: "长期配合是否稳定顺畅", example: "例如：合作结束后，是先看成果，还是先看是否可靠、好沟通、可持续。" },
  { id: "d48", dimension: "C", prompt: "重要判断临门前，哪种倾向更接近？", leftLabel: "先在有限信息下定方向", rightLabel: "再查一次避免凭印象", example: "例如：要做判断前，是先按已有信息推进，还是再核一次资料。" },
];
